name: CI/CD Pipeline for Azure Kubernetes Service

on:
  push:
    branches:
      - main  # Trigger CI/CD on push to main branch

jobs:
  # CI Job: Build and Push Docker Image to ACR
  ci:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (Optional but Recommended for Multi-Platform Builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/my-app:${{ github.sha }} .

      # Step 4: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # Step 5: Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/my-app:${{ github.sha }}
  # CD Job: Deploy Docker Image to AKS
  deploy:
    runs-on: ubuntu-latest
    needs: ci  # This job depends on the successful completion of the 'ci' job
    steps:
      # Step 1: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
        with:
          version: '2.30.0'

      # Step 2: Azure login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Service Principal credentials

      # Step 3: Set up Kubernetes Context
      - name: Set up Kubernetes context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }} --overwrite-existing

      # Step 4: Deploy Docker image to AKS
      - name: Deploy Docker image to AKS
        run: |
          kubectl set image deployment/my-app my-app=${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/my-app:${{ github.sha }} --record
          kubectl rollout status deployment/my-app

      # Step 5: Optional - Clean up Azure CLI
      - name: Logout from Azure CLI
        run: az logout
